mulimr_dir: "/workspace/MultiMR/"
mulimr_data_dir: "embedding/"
device: cuda
model:
  pretrained_clip_model_dir: ViT-L/14 
  merge: score
  ckpt_config: 
    ckpt_dir: "checkpoint/"
    ckpt_name: vit-l-14/simclr_true/add_task/_epoch_9.pth

retrieval_config:
  results_dir_name: retrieval_results
  qrel_dir_name:  qrels 
  embed_dir_name: embedding 
  index_dir_name: test