mulimr_dir: /workspace/MultiMR/
embed_dir_name: embedding/
#expt_name: VIT-L-14 #biomedclip clip

model:
  name: CLIPScoreFusion #CLIPScoreFusion CLIPBIOcoreFusion
  pretrained_clip_model_dir: ViT-L/14
  # pretrained_clip_model_dir: hf-hub:microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224
  merge: score
  ckpt_config: 
    ckpt_dir: checkpoint/  
    # ckpt_name: vit-b-32/add_none_epoch_10.pth
    # ckpt_name: vit-b-32/simclr_false/_epoch_10.pth
    # ckpt_name: vit-b-16/add_none_epoch_10.pth
    #ckpt_name: vit-l-14/simclr_false/_epoch_10.pth
    #ckpt_name: vit-b-32/add_none_epoch_10.pth
    # ckpt_name: vit-b-32/simclr_false/add_task/_epoch_10.pth
    #ckpt_name: vit-l-14/mlp/_epoch_10.pth
    #ckpt_name: vit-l-14/weight/_epoch_10.pth
    # ckpt_name: simclr_true/add_task/_epoch_best.pth

    
    # ckpt_name: vit-l-14/score/simclr_false/_epoch_10.pth
    # ckpt_name: vit-b/32/score/simclr_false/_epoch_10.pth
    ckpt_name: vit-l-14/final_epoch_best.pth
    
    
dataset:
  name: Jiiwonn/roco2-question-id-dataset

split: test
device: cuda

