mulimr_dir: "/workspace/MultiMR/"
embed_dir_name: embedding/
mulimr_data_dir: "/workspace/MultiMR/embedding/"
model_name: vit-l-14/weight/_epoch_10.pth
split: test
experiment:
  path_suffix: my_rocov2_exp_test_img_txt 

index_config:
    faiss_config:
        idx_type: Flat
        dim: 768
        metric: METRIC_INNER_PRODUCT        
    embed_dir_name: embed  #
    index_dir_name: index
    cand_pools_config: # FAISS 인덱스를 생성할 후보 풀 설정
      enable_idx: True
      cand_pools_name_to_idx: ["rocov2-question"]

retrieval_config:
  results_dir_name: retrieval_results
  qrel_dir_name:  qrels # QREL dir
  embed_dir_name: embedding 


  raw_retrieval: False 
  retrieve_image_text_pairs: False 
  write_to_tsv: True 

  test_datasets_config:
    enable_retrieve: True 
    datasets_name: ["rocov2-questions-radiology"] 
    correspond_cand_pools_name: ["rocov2-questions-radiology"] 
    correspond_qrels_name: ["rocov2-questions-radiology"]
    correspond_metrics_name: ["Recall@1, Recall@5, Recall@10, Recall@50, Recall@100"] # 평가할 지표


    val_datasets_config:
      enable_retrieve: True
    train_datasets_config:
      enable_retrieve: True
